name: CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: CD
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Connect and deploy
      env:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
      run: |
        ~/deployment.sh
